package com.example.github_api_application.model.vo

data class User(
		val login: String,
		val id: Int,
		val avatar_url: String,
		val gravatar_id: String,
		val url: String,
		val html_url: String,
		val followers_url: String,
		val following_url: String,
		val gists_url: String,
		val starred_url: String,
		val subscriptions_url: String,
		val organizations_url: String,
		val repos_url: String,
		val events_url: String,
		val received_events_url: String,
		val type: String,
		val site_admin: Boolean,
		val name: String,
		val company: Any,
		val blog: String,
		val location: Any,
		val email: String,
		val hireable: Any,
		val bio: Any,
		val public_repos: Int,
		val public_gists: Int,
		val followers: Int,
		val following: Int,
		val created_at: String,
		val updated_at: String,
		val username: String,

		var access_token: String?
)